### ISSUE TITLE
Add an option to quit the game

### ISSUE THREAD

**Issue by Vaarun-Kamath** [Vaarun-Kamath/Monopoly-Game#1]
# Description
As of now there is no option for the player to end the game in between, user has to Ctrl+C the terminal.
- Add an option for the player to quit the game
- **Extra points**: If you can save the state of the game on quit, and have a resume option when the user opens the game again

**Comment by prerana1809** [comment]
I want to be assigned to this.

**Comment by Vaarun-Kamath** [comment]
You have been assigned

**Comment by Shaatvika** [comment]
Can I be assigned?

**Comment by Rhn14** [comment]
can i be assigned?

**Comment by Sanjaya2204** [comment]
id like to be assigned

**Comment by Sarah-Alex** [comment]
Can I be assigned?

**Comment by maverickayush7** [comment]
varun , can i get it assigned ?

**Comment by Chatter-77** [comment]
Can i get assigned to this issue?

**Comment by Suhaniverma2004** [comment]
can i get assigned?

**Comment by RishavSinha20** [comment]
please assign me

**Comment by komulannister** [comment]
can i get assigned to this?

**Comment by anshiiJ** [comment]
can i get assigned to this?

**Comment by neethanm** [comment]
can i be assigned to this?

**Comment by pj1840** [comment]
can i be assigned to this PLSSSSSSSSSSS

**Comment by Aakriti-2334** [comment]
can i get assigned?

**Comment by ShankyTaco** [comment]
Can you assign this to me?

**Comment by Vaarun-Kamath** [comment]
@prerana1809 I need an update by 9, else I will reassign this issue

**Comment by ShankyTaco** [comment]
> @prerana1809 I need an update by 9, else I will reassign this issue

Could I please be assigned the issue if it gets dropped? I haven't been assigned to work on anything so far and I would appreciate it if you could give it to me :)

**Comment by neethanm** [comment]
can i get assigned to #1

**Comment by Vaarun-Kamath** [comment]
@prerana1809 you have not given me an update. I am reassigning this issue

**Comment by Vaarun-Kamath** [comment]
@ShankyTaco You have been assigned this issue

**Comment by deeksha-s-jain** [comment]
can i get assigned to this?

**Comment by Pro696969** [comment]
can i get assigned to this ?

**Comment by Archit-Rode** [comment]
Can i get assigned

**Comment by LalithaTanmayee** [comment]
Can I get this assigned?

**Comment by Vaarun-Kamath** [comment]
@ShankyTaco do you have any updates?

**Comment by PandaTGOS** [comment]
Can I get assigned to this ?

**Comment by ShankyTaco** [comment]
> @ShankyTaco do you have any updates?

Yes I am almost done, I just finished dinner

**Comment by ShankyTaco** [comment]
Will submit in a few minutes

**Comment by 411sst** [comment]
can i get assigned if this is still open?

**Comment by pratham-exe** [comment]
can i get assigned if it is still open

**Comment by ShankyTaco** [comment]
I choose to drop this issue

**Comment by Vaarun-Kamath** [comment]
@Pro696969 You have been assigned this issue
