### ISSUE TITLE
Dice needs to be visualized

### ISSUE THREAD

**Issue by Vaarun-Kamath** [Vaarun-Kamath/Monopoly-Game#2]
# Description
When the game starts, each player needs to roll the dice on pressing ' R ' and the C code generates random number from 1 to 6.
- Currently it only prints the number of the dice that has been rolled
- Along with a number, show the image (ASCII Art) of the dice on the side

**Comment by Rhn14** [comment]
can i be assigned?

**Comment by Vaarun-Kamath** [comment]
@Rhn14 you have been assigned

**Comment by Drakonxd786** [comment]
can i be assigned to this?

**Comment by Judoca** [comment]
May i be assigned to this please?

**Comment by Suhaniverma2004** [comment]
can i get assigned?

**Comment by RishavSinha20** [comment]
please assign me

**Comment by Ankitha3435** [comment]
can i get assigned?

**Comment by Ankitha3435** [comment]
can i get assigned

**Comment by LalithaTanmayee** [comment]
Assign to me please

**Comment by karun1763** [comment]
assign this to me

**Comment by neethanm** [comment]
can i be assigned to this?

**Comment by Python-is-better-than-Java** [comment]
Can I be assigned this?

**Comment by Vaarun-Kamath** [comment]
@Rhn14 I need an issue by 9, else I will reassign this issue

**Comment by Advaith2805** [comment]
Can i get assigned to this

**Comment by harveen-10** [comment]
can i be assigned to this?

**Comment by ShankyTaco** [comment]
Could you assign this issue to me?

**Comment by neethanm** [comment]
can i get assigned to #2

**Comment by Vaarun-Kamath** [comment]
@Advaith2805 you have been assigned

**Comment by Shiva4113** [comment]
Can i do this?

**Comment by Vaarun-Kamath** [comment]
@Advaith2805 any updates?

**Comment by Advaith2805** [comment]
I have made a pull request

**Comment by 411sst** [comment]
can i get assigned if this is still open?

**Comment by Vaarun-Kamath** [comment]
@karun1763 you have been assigned this issue

**Comment by ghost** [comment]
Can i be assigned this issue

**Comment by PandaTGOS** [comment]
Can I get assigned to this ?
