### ISSUE TITLE
Add more chance cards

### ISSUE THREAD

**Issue by Vaarun-Kamath** [Vaarun-Kamath/Monopoly-Game#3]
# Desctiption
There are a total of 14 chance cards
- Add 2 more chance cards in the game
- Search for the comment " CHANCE LOGIC " in the code, which has the logic for chance

**Comment by Shiva4113** [comment]
Hello, can I get assigned to this issue

**Comment by Vaarun-Kamath** [comment]
You have been assigned

**Comment by Rhn14** [comment]
can i be assigned?

**Comment by ManushriJ** [comment]
can i get assigned

**Comment by icantype1912** [comment]
Can i get assigned to this issue?

**Comment by Chatter-77** [comment]
Can i get assigned to this issue?

**Comment by Suhaniverma2004** [comment]
can i get assigned?

**Comment by RishavSinha20** [comment]
please assign me

**Comment by komulannister** [comment]
can i get assigned to this?

**Comment by anshiiJ** [comment]
pls assign this?

**Comment by HemaShree0408** [comment]
can i get assigned

**Comment by neethanm** [comment]
can i get assigned to this issue

**Comment by pj1840** [comment]
can i get assigned to this pls

**Comment by euphoricair7** [comment]
Could You assign me this issue?

**Comment by euphoricair7** [comment]
Could You assign me this issue?

**Comment by Aakriti-2334** [comment]
can i get assigned?
